CLASS lhc_ZHELLO_ORDER_ENTITY DEFINITION INHERITING FROM cl_abap_behavior_handler.
  PRIVATE SECTION.

    METHODS CancelOrder FOR MODIFY
      IMPORTING keys FOR ACTION zhello_order_entity~CancelOrder.

ENDCLASS.

CLASS lhc_ZHELLO_ORDER_ENTITY IMPLEMENTATION.

  METHOD CancelOrder.


  ENDMETHOD.

ENDCLASS.
